services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-global
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # Redis Insight UI
    volumes:
      - ./redis-data:/data  # Persist Redis data
    networks:
      - global-services-network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql-global
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  # MySQL port
    volumes:
      - ./mysql-data:/var/lib/mysql  # Persist MySQL data
    networks:
      - global-services-network
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8888:80"  # Expose phpMyAdmin on port 8888
    environment:
      PMA_HOST: mysql-global  # Connect phpMyAdmin to MySQL container
      PMA_USER: root          # MySQL user
      PMA_PASSWORD: root      # MySQL password
      PMA_ARBITRARY: 1        # Allow connections to arbitrary MySQL hosts
    networks:
      - global-services-network
    restart: always


networks:
  global-services-network:
    name: global-services-network  # Explicitly define the network name
    driver: bridge